#!/usr/bin/env python3
"""
Patch AnalysisPage.jsx v5:
1. Remove client-dossiers-section (pills hidden at startup)
2. Move "Charger factures" button below manual-search section
3. Filter items with line_count > 0 in handleLoadDemoSample
4. Update success message to list dossier names
"""
from pathlib import Path

TARGET = Path(__file__).resolve().parent.parent / "frontend/src/pages/AnalysisPage.jsx"
src = TARGET.read_text(encoding="utf-8")

# ─── 1. Filter items with line_count > 0 in handleLoadDemoSample ─────────────
OLD_ITEMS = (
    "      const payload = await fetchDemoFolderSample(3);\n"
    "      const items = Array.isArray(payload?.items) ? payload.items : [];\n"
    "      setQueueItems(items);"
)
NEW_ITEMS = (
    "      const payload = await fetchDemoFolderSample(3);\n"
    "      const rawItems = Array.isArray(payload?.items) ? payload.items : [];\n"
    "      const items = rawItems.filter((inv) => (inv.line_count ?? inv.exploitable_lines_count ?? 0) > 0);\n"
    "      if (items.length === 0 && rawItems.length > 0) {\n"
    "        setQueueErrorMessage(\"Aucune facture exploitable trouv\u00e9e dans cet \u00e9chantillon.\");\n"
    "      }\n"
    "      setQueueItems(items);"
)
assert src.count(OLD_ITEMS) == 1, f"ITEMS anchor count={src.count(OLD_ITEMS)}"
src = src.replace(OLD_ITEMS, NEW_ITEMS)

# ─── 2. Update success message with dossier names ─────────────────────────────
OLD_MSG = (
    "      if (items.length > 0) {\n"
    "        const folders = [\"BOUCHERIE IFRI\", \"ASSAINIS\", \"UNIVERS DU PAIN\", \"PROSERVICES\", \"PRIM D\u00c9M\u00c9NAGEMENT\"];\n"
    "        setSuccessMessage(`${items.length} factures charg\u00e9es depuis ${folders.length} dossiers clients.`);\n"
    "      }"
)
NEW_MSG = (
    "      if (items.length > 0) {\n"
    "        setSuccessMessage(`${items.length} factures exploit. charg\u00e9es \u2014 BOUCHERIE IFRI, ASSAINIS, UNIVERS DU PAIN, PROSERVICES, PRIM D\u00c9M\u00c9NAGEMENT.`);\n"
    "      }"
)
assert src.count(OLD_MSG) == 1, f"MSG anchor count={src.count(OLD_MSG)}"
src = src.replace(OLD_MSG, NEW_MSG)

# ─── 3. Replace the whole client-dossiers-section + manual-search + closing </details>
# with: manual-search first, then "Charger factures" button after it
OLD_BLOCK = (
    "\n        {/* \u2500\u2500 Dossiers clients \u2500\u2500 */}\n"
    "        <div className=\"client-dossiers-section\">\n"
    "          <div className=\"client-dossiers-header\">\n"
    "            <span className=\"client-dossiers-title\">Dossiers clients</span>\n"
    "            <span className=\"client-dossiers-subtitle\">\n"
    "              Charge les factures d\u2019un dossier r\u00e9el sans scanner toute CouchDB.\n"
    "            </span>\n"
    "          </div>\n"
    "          <div className=\"client-dossiers-pills\">\n"
    "            {[\n"
    "              { name: \"BOUCHERIE IFRI\",               label: \"BOUCHERIE IFRI\",    metier: \"Boucherie\"    },\n"
    "              { name: \"ASSAINIS\",                      label: \"ASSAINIS\",          metier: \"BTP\"          },\n"
    "              { name: \"BOULANGERIE L'UNIVERS DU PAIN\", label: \"UNIVERS DU PAIN\",   metier: \"Boulangerie\"  },\n"
    "              { name: \"PROSERVICES AMBULANCES\",        label: \"PROSERVICES\",       metier: \"Transport\"    },\n"
    "              { name: \"PRIM DEMENAGEMENT\",             label: \"PRIM D\u00c9M\u00c9NAGEMENT\",    metier: \"D\u00e9m\u00e9nagement\" },\n"
    "            ].map((d) => (\n"
    "              <button\n"
    "                key={d.name}\n"
    "                type=\"button\"\n"
    "                className={`client-dossier-pill${activeDossier === d.name ? \" active\" : \"\"}`}\n"
    "                onClick={() => handleLoadDossier(d)}\n"
    "                disabled={loadingInvoices}\n"
    "              >\n"
    "                <span className=\"client-dossier-pill-badge\">{d.metier}</span>\n"
    "                {loadingInvoices && activeDossier === d.name ? (\n"
    "                  <LoaderCircle size={11} className=\"spin\" />\n"
    "                ) : null}\n"
    "                {d.label}\n"
    "              </button>\n"
    "            ))}\n"
    "          </div>\n"
    "          {activeDossier ? (\n"
    "            <span className=\"analysis-loaded-source-label\">\n"
    "              <Database size={11} />\n"
    "              Dossier charg\u00e9\xa0: {activeDossier}\n"
    "            </span>\n"
    "          ) : null}\n"
    "          <div className=\"client-dossiers-actions\">\n"
    "            <button\n"
    "              type=\"button\"\n"
    "              className=\"secondary-btn compact\"\n"
    "              onClick={handleLoadDemoSample}\n"
    "              disabled={loadingInvoices}\n"
    "              title=\"Charge 3 factures par dossier depuis les 5 dossiers clients r\u00e9els\"\n"
    "            >\n"
    "              {loadingInvoices && !activeDossier ? (\n"
    "                <LoaderCircle size={14} className=\"spin\" />\n"
    "              ) : (\n"
    "                <Database size={14} />\n"
    "              )}\n"
    "              Charger factures\n"
    "            </button>\n"
    "            {!activeDossier && !loadingInvoices ? (\n"
    "              <span className=\"client-dossiers-hint\">\n"
    "                ou cliquez sur un dossier ci-dessus\n"
    "              </span>\n"
    "            ) : null}\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        {/* \u2500\u2500 Recherche manuelle (accord\u00e9on) \u2500\u2500 */}\n"
    "        <details className=\"manual-search-section\">\n"
    "          <summary className=\"manual-search-summary\">\n"
    "            <SearchCheck size={14} />\n"
    "            Recherche manuelle\n"
    "          </summary>\n"
    "          <div className=\"manual-search-body\">\n"
    "            <div className=\"analysis-field-grid analysis-queue-search-grid\">\n"
    "              <label className=\"analysis-field\">\n"
    "                <span>Fournisseur</span>\n"
    "                <input\n"
    "                  value={queueFilters.supplier}\n"
    "                  onChange={(event) => handleQueueFilterInput(\"supplier\", event.target.value)}\n"
    "                  placeholder=\"Ex : Bouygues Telecom\"\n"
    "                />\n"
    "              </label>\n"
    "              <label className=\"analysis-field\">\n"
    "                <span>Client</span>\n"
    "                <input\n"
    "                  value={queueFilters.client}\n"
    "                  onChange={(event) => handleQueueFilterInput(\"client\", event.target.value)}\n"
    "                  placeholder=\"Ex : Boucherie Mouad\"\n"
    "                />\n"
    "              </label>\n"
    "              <label className=\"analysis-field\">\n"
    "                <span>Code APE</span>\n"
    "                <input\n"
    "                  value={queueFilters.ape}\n"
    "                  onChange={(event) => handleQueueFilterInput(\"ape\", event.target.value)}\n"
    "                  placeholder=\"Ex : 4722Z\"\n"
    "                />\n"
    "              </label>\n"
    "            </div>\n"
    "            <div className=\"analysis-engine-actions analysis-queue-search-action\">\n"
    "              <button\n"
    "                type=\"button\"\n"
    "                className=\"primary-btn\"\n"
    "                onClick={handleQueueSearch}\n"
    "                disabled={loadingInvoices}\n"
    "              >\n"
    "                {loadingInvoices ? (\n"
    "                  <LoaderCircle size={16} className=\"spin\" />\n"
    "                ) : (\n"
    "                  <SearchCheck size={16} />\n"
    "                )}\n"
    "                Rechercher dans CouchDB\n"
    "              </button>\n"
    "            </div>\n"
    "          </div>\n"
    "        </details>"
)

NEW_BLOCK = (
    "\n"
    "        {/* \u2500\u2500 Recherche manuelle (\u00e0 plat) \u2500\u2500 */}\n"
    "        <div className=\"manual-search-flat\">\n"
    "          <div className=\"analysis-field-grid analysis-queue-search-grid\">\n"
    "            <label className=\"analysis-field\">\n"
    "              <span>Fournisseur</span>\n"
    "              <input\n"
    "                value={queueFilters.supplier}\n"
    "                onChange={(event) => handleQueueFilterInput(\"supplier\", event.target.value)}\n"
    "                placeholder=\"Ex : Bouygues Telecom\"\n"
    "              />\n"
    "            </label>\n"
    "            <label className=\"analysis-field\">\n"
    "              <span>Client</span>\n"
    "              <input\n"
    "                value={queueFilters.client}\n"
    "                onChange={(event) => handleQueueFilterInput(\"client\", event.target.value)}\n"
    "                placeholder=\"Ex : Boucherie Mouad\"\n"
    "              />\n"
    "            </label>\n"
    "            <label className=\"analysis-field\">\n"
    "              <span>Code APE</span>\n"
    "              <input\n"
    "                value={queueFilters.ape}\n"
    "                onChange={(event) => handleQueueFilterInput(\"ape\", event.target.value)}\n"
    "                placeholder=\"Ex : 4722Z\"\n"
    "              />\n"
    "            </label>\n"
    "          </div>\n"
    "          <div className=\"manual-search-flat-actions\">\n"
    "            <button\n"
    "              type=\"button\"\n"
    "              className=\"secondary-btn compact\"\n"
    "              onClick={handleQueueSearch}\n"
    "              disabled={loadingInvoices}\n"
    "            >\n"
    "              {loadingInvoices ? (\n"
    "                <LoaderCircle size={14} className=\"spin\" />\n"
    "              ) : (\n"
    "                <SearchCheck size={14} />\n"
    "              )}\n"
    "              Rechercher dans CouchDB\n"
    "            </button>\n"
    "            <button\n"
    "              type=\"button\"\n"
    "              className=\"primary-btn\"\n"
    "              onClick={handleLoadDemoSample}\n"
    "              disabled={loadingInvoices}\n"
    "              title=\"Charge ~3 factures par dossier depuis les 5 dossiers clients r\u00e9els\"\n"
    "            >\n"
    "              {loadingInvoices ? (\n"
    "                <LoaderCircle size={14} className=\"spin\" />\n"
    "              ) : (\n"
    "                <Database size={14} />\n"
    "              )}\n"
    "              Charger factures\n"
    "            </button>\n"
    "          </div>\n"
    "        </div>"
)

count = src.count(OLD_BLOCK)
assert count == 1, f"BLOCK anchor count={count}"
src = src.replace(OLD_BLOCK, NEW_BLOCK)

TARGET.write_text(src, encoding="utf-8")
print(f"\u2705 Patch v5 applied. File length: {len(src)} chars")
